# The rainmaker config file
uconf_path:  '~/.rainmaker/conf.yml'

# Icons for the GUI
icons:
    0:
        file: 'code-0.png'
        msg: 'Transfer Successfull'
    1:
        file: 'code-1.png'
        msg: 'Some conflicts exist...'
    2:
        file: 'code-2.png'
        msg: 'Non fatal error occurred'
    3:  
        file: 'code-3.png'
        msg: 'Fatal error occurred'
    90: 
        file: 'code-90.png'
        msg: 'Initializing...'
    91: 
        file: 'code-91.png'
        msg: 'Contacting Server...'
    98: 
        file: 'code-98.png'
        msg: 'Unable to contact Server...'
    99: 
        file: 'code-99.png'
        msg: 'Unknown event occurred'

# flags that can be used to construct a command
cmd_flags:
    root:           '?root_full?'
    src_dir_rel:    '?src_dir_rel?'
    src_dir_full:   '?src_dir_full?'
    src_file_rel:   '?src_file_rel?'
    src_file_full:  '?src_file_full?'
    src_file_name:  '?src_file_name?'
    src_file_type:  '?src_file_type?'
    dest_dir_rel:   '?dest_dir_rel?'
    dest_dir_full:  '?dest_dir_full?'
    dest_file_rel:  '?dest_file_rel?'
    dest_file_full: '?dest_file_full?'
    dest_file_name: '?dest_file_name?'
    dest_file_type: '?dest_file_type?'
    event_type: '?event_type?'
    cmd_macros: '?cmd_macro?'

profile_flags:
    type: rainmaker_data
    desc: dynamic profile variables
    default: null
    val:
        current_user: {default: null, desc: current user name, type: flag, val: null}

templates:
    unison:
        type: rainmaker_data
        desc: unison template profile
        default: null
        val:
            title:
                val: null
                default: rainmaker-unison
                type: str
                desc: 'profile name'
            prf:
                val: null
                default: null
                type: str
                desc: 'unison profile name'
            user:
                val: null
                default: '?current_user?'
                type: str
                desc: 'server user name'
            port:
                val: null
                default: 22
                type: int
                desc: 'server ssh port'
            address:
                val: null
                default: localhost 
                type: str
                desc: 'server address'
            ssh_key_path:
                val: null
                default: id_rsa
                type: str
                desc: 'ssh private key (path optional)'
            local_root:
                val: null
                default: ~/sync
                type: str
                desc: 'local root'
            remote_path:
                val: null
                default: /home/rainmaker/?user?
                type: str
                desc: 'remote root'
            remote_root:
                val: null
                default: 'ssh://?user?@?address?:?port?/?remote_path?'
                type: str
                desc: null
            max_backups:
                val: null
                default: 10
                type: int
                desc: 'max backups'
            cmds:
                type: rainmaker_data
                default:
                val:
                    all: 
                        type: str
                        val: null
                        default: '?file? "?src_file_rel?"'
                        desc: 'all file system events'
                    moved: 
                        type: arr
                        val:
                        default:
                            - '?file? "?src_file_rel?"'
                            - '?file? "?dest_file_rel?"'
                        desc: 'file moved events'
                    moved_in:
                        type: arr
                        val: null
                        default: null
                        desc: 'file moved into sync path'
                    moved_out:
                        type: arr
                        val: null
                        default: null
                        desc: 'file moved out of sync path'
                    moved_within:
                        type: arr
                        val: null
                        default: null
                        desc: 'file moved within sync path'
                    deleted:
                        type: arr
                        val: null
                        default: null
                        desc: 'file deleted'
                    created:
                        type: arr
                        val: null
                        default: null
                        desc: 'file created'
                    modified:
                        type: arr
                        val: null
                        default: null
                        desc: 'file modified'
                    startup: 
                        type: arr
                        val: null
                        default:
                            - '?base?'
                        desc: 'startup commands'
                    shutdown:
                        type: arr
                        val: null
                        default: null
                        desc: 'shutdown commands'
                desc: 'file system event flags'
            cmd_macros:
                type: rainmaker_data
                default:
                val:
                    ?unison?:
                        type: str
                        val:
                        default: unison
                        desc: 'Unison command path'
                    ?file?:
                        type: str
                        val:
                        default: '?unison? ?prf? -ui text -sshargs "-i ?ssh_key? " -path' 
                        desc: 'Unison command for file system event'
                    ?base?:
                        type: str
                        val:
                        default: '?unison? ?prf? -ui text -sshargs "-i ?ssh_key? "'
                        desc: 'Unison command for full sync'
                desc: 'command macros'
templates_old:
    unison:    
        name: ''
        type: unison
        description: ''
        prf: ''
        max_threads: 2
        auto_start:  true
        use_cmd_all: false
        recursive: true
        cmds:
            all: '?file? "?src_file_rel?"' 
            moved: 
                - '?file? "?src_file_rel?"'
                - '?file? "?dest_file_rel?"'
            moved_in:
            moved_out:
            moved_within:
            deleted:
            created:
            modified:
            startup: '?base?' 
            shutdown:
        cmd_macros:
            ?unison?: unison
            ?file?: '?unison? ?prf? -ui text -sshargs "-i ?ssh_key? " -path' 
            ?base?: '?unison? ?prf? -ui text -sshargs "-i ?ssh_key? "'
