# The rainmaker config file
uconf_path:  '~/.rainmaker/conf.yml'

# Icons for the GUI
icons:
    0:
        file: 'code-0.png'
        msg: 'Transfer Successfull'
    1:
        file: 'code-1.png'
        msg: 'Some conflicts exist...'
    2:
        file: 'code-2.png'
        msg: 'Non fatal error occurred'
    3:  
        file: 'code-3.png'
        msg: 'Fatal error occurred'
    90: 
        file: 'code-90.png'
        msg: 'Initializing...'
    91: 
        file: 'code-91.png'
        msg: 'Contacting Server...'
    98: 
        file: 'code-98.png'
        msg: 'Unable to contact Server...'
    99: 
        file: 'code-99.png'
        msg: 'Unknown event occurred'

# flags that can be used to construct a command
cmd_flags:
    root:           '?root_full?'
    src_dir_rel:    '?src_dir_rel?'
    src_dir_full:   '?src_dir_full?'
    src_file_rel:   '?src_file_rel?'
    src_file_full:  '?src_file_full?'
    src_file_name:  '?src_file_name?'
    src_file_type:  '?src_file_type?'
    dest_dir_rel:   '?dest_dir_rel?'
    dest_dir_full:  '?dest_dir_full?'
    dest_file_rel:  '?dest_file_rel?'
    dest_file_full: '?dest_file_full?'
    dest_file_name: '?dest_file_name?'
    dest_file_type: '?dest_file_type?'
    event_type: '?event_type?'
    cmd_macros: '?cmd_macro?'

profile_flags:
    local_root: '?local_root?'
    ssh_key: '?ssh_key?'

questions:
    unison:
        title:
            ans: null
            default: rainmaker-unison
            type: str
            q: 'profile name:'
        user:
            ans: null
            default: null
            type: str
            q: 'server user name:'
        port:
            ans: null
            default: 22
            type: int
            q: 'server ssh port:'
        address:
            ans: null
            default: localhost 
            type: str
            q: 'server address:'
        ssh_key_path:
            ans: null
            default: id_rsa
            type: str
            q: 'ssh private key (path optional):'
        local_root:
            ans: null
            default: ~/sync
            type: str
            q: 'local root:'
        remote_path:
            ans: null
            default: /home/rainmaker/?user?
            type: str
            q: 'remote root:'
        remote_root:
            ans: null
            default: 'ssh://?user?@?address?:?port?/?remote_path?'
            type: str
            q: null
        max_backups:
            ans: null
            default: 10
            type: int
            q: 'max backups:'

templates:
    unison:    
        name: ''
        type: unison
        description: ''
        prf: ''
        max_threads: 2
        auto_start:  true
        use_cmd_all: false
        recursive: true
        cmds:
            all: '?file? "?src_file_rel?"' 
            moved: 
                - '?file? "?src_file_rel?"'
                - '?file? "?dest_file_rel?"'
            moved_in:
            moved_out:
            moved_within:
            deleted:
            created:
            modified:
            startup: '?base?' 
            shutdown:
        cmd_macros:
            ?unison?: unison
            ?file?: '?unison? ?prf? -ui text -sshargs "-i ?ssh_key? " -path' 
            ?base?: '?unison? ?prf? -ui text -sshargs "-i ?ssh_key? "'
