#!/usr/bin/python
"""
This file is part of Rainmaker.

    Rainmaker is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Rainmaker is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Rainmaker.  If not, see <http://www.gnu.org/licenses/>.
"""
from time import sleep
from rainmaker_app.app.initialize import AppParser
from rainmaker_app import boot


def main():

    #########
    # start logging to STDOUT
    app = boot.Rainmaker()
     
    #################
    # process command line arguments
    parser = AppParser(app)
    parser.parse_args()
    
    try:
        app.init()
        while True:
            app.loop.once()
    except KeyboardInterrupt:
        pass
    app.shutdown()

if __name__ == "__main__":
    main()
