# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'profile-basic.ui'
#
# Created: Wed May  9 08:54:06 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName(_fromUtf8("Frame"))
        Frame.resize(625, 330)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Frame.sizePolicy().hasHeightForWidth())
        Frame.setSizePolicy(sizePolicy)
        Frame.setMinimumSize(QtCore.QSize(625, 330))
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Frame)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(9)
        self.horizontalLayout_9.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(Frame)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.txt_name = QtGui.QLineEdit(Frame)
        self.txt_name.setObjectName(_fromUtf8("txt_name"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.txt_name)
        self.label_3 = QtGui.QLabel(Frame)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.txt_local_root = QtGui.QLineEdit(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_local_root.sizePolicy().hasHeightForWidth())
        self.txt_local_root.setSizePolicy(sizePolicy)
        self.txt_local_root.setMinimumSize(QtCore.QSize(176, 0))
        self.txt_local_root.setObjectName(_fromUtf8("txt_local_root"))
        self.horizontalLayout_2.addWidget(self.txt_local_root)
        self.btn_local_root = QtGui.QToolButton(Frame)
        self.btn_local_root.setObjectName(_fromUtf8("btn_local_root"))
        self.horizontalLayout_2.addWidget(self.btn_local_root)
        self.formLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.formLayout)
        self.line = QtGui.QFrame(Frame)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_8 = QtGui.QLabel(Frame)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_8)
        self.txt_address = QtGui.QLineEdit(Frame)
        self.txt_address.setObjectName(_fromUtf8("txt_address"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.txt_address)
        self.label_2 = QtGui.QLabel(Frame)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.txt_remote_root = QtGui.QLineEdit(Frame)
        self.txt_remote_root.setObjectName(_fromUtf8("txt_remote_root"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.txt_remote_root)
        self.label_7 = QtGui.QLabel(Frame)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_7)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.txt_port = QtGui.QSpinBox(Frame)
        self.txt_port.setMinimumSize(QtCore.QSize(88, 0))
        self.txt_port.setMaximum(65535)
        self.txt_port.setProperty("value", 22)
        self.txt_port.setObjectName(_fromUtf8("txt_port"))
        self.horizontalLayout.addWidget(self.txt_port)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.formLayout_3.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.verticalLayout.addLayout(self.formLayout_3)
        self.line_3 = QtGui.QFrame(Frame)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout.addWidget(self.line_3)
        self.formLayout_5 = QtGui.QFormLayout()
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.formLayout_5.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.label_5 = QtGui.QLabel(Frame)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.txt_ssh_key = QtGui.QLineEdit(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_ssh_key.sizePolicy().hasHeightForWidth())
        self.txt_ssh_key.setSizePolicy(sizePolicy)
        self.txt_ssh_key.setMinimumSize(QtCore.QSize(176, 0))
        self.txt_ssh_key.setObjectName(_fromUtf8("txt_ssh_key"))
        self.horizontalLayout_4.addWidget(self.txt_ssh_key)
        self.btn_ssh_key_dialog = QtGui.QToolButton(Frame)
        self.btn_ssh_key_dialog.setObjectName(_fromUtf8("btn_ssh_key_dialog"))
        self.horizontalLayout_4.addWidget(self.btn_ssh_key_dialog)
        self.formLayout_5.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label_4 = QtGui.QLabel(Frame)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.txt_unison_path = QtGui.QLineEdit(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_unison_path.sizePolicy().hasHeightForWidth())
        self.txt_unison_path.setSizePolicy(sizePolicy)
        self.txt_unison_path.setMinimumSize(QtCore.QSize(176, 0))
        self.txt_unison_path.setObjectName(_fromUtf8("txt_unison_path"))
        self.horizontalLayout_3.addWidget(self.txt_unison_path)
        self.btn_unison_path_dialog = QtGui.QToolButton(Frame)
        self.btn_unison_path_dialog.setObjectName(_fromUtf8("btn_unison_path_dialog"))
        self.horizontalLayout_3.addWidget(self.btn_unison_path_dialog)
        self.formLayout_5.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.btn_save_2 = QtGui.QPushButton(Frame)
        self.btn_save_2.setObjectName(_fromUtf8("btn_save_2"))
        self.horizontalLayout_11.addWidget(self.btn_save_2)
        self.formLayout_5.setLayout(3, QtGui.QFormLayout.FieldRole, self.horizontalLayout_11)
        self.verticalLayout.addLayout(self.formLayout_5)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_9.addLayout(self.verticalLayout)
        self.line_2 = QtGui.QFrame(Frame)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_9.addWidget(self.line_2)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_12 = QtGui.QLabel(Frame)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_12)
        self.label_13 = QtGui.QLabel(Frame)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_13)
        self.label_14 = QtGui.QLabel(Frame)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_14)
        self.label_15 = QtGui.QLabel(Frame)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_15)
        self.label_16 = QtGui.QLabel(Frame)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.FieldRole, self.label_16)
        self.label_17 = QtGui.QLabel(Frame)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.label_17)
        self.label_18 = QtGui.QLabel(Frame)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.label_18)
        self.label_19 = QtGui.QLabel(Frame)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_19)
        self.label_20 = QtGui.QLabel(Frame)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.formLayout_4.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_20)
        self.label_21 = QtGui.QLabel(Frame)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.formLayout_4.setWidget(5, QtGui.QFormLayout.FieldRole, self.label_21)
        self.label_11 = QtGui.QLabel(Frame)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_11)
        self.label_24 = QtGui.QLabel(Frame)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.label_24)
        self.verticalLayout_3.addLayout(self.formLayout_4)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.btn_start = QtGui.QPushButton(Frame)
        self.btn_start.setEnabled(False)
        self.btn_start.setObjectName(_fromUtf8("btn_start"))
        self.horizontalLayout_6.addWidget(self.btn_start)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.btn_save = QtGui.QPushButton(Frame)
        self.btn_save.setObjectName(_fromUtf8("btn_save"))
        self.horizontalLayout_6.addWidget(self.btn_save)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_9.addLayout(self.verticalLayout_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(QtGui.QApplication.translate("Frame", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Frame", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.txt_name.setPlaceholderText(QtGui.QApplication.translate("Frame", "Name of profile", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Frame", "Local sync path:", None, QtGui.QApplication.UnicodeUTF8))
        self.txt_local_root.setPlaceholderText(QtGui.QApplication.translate("Frame", "Path of folder to watch", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_local_root.setText(QtGui.QApplication.translate("Frame", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Frame", "Server address:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Frame", "Server sync path:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Frame", "Server ssh port", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Frame", "ssh private key", None, QtGui.QApplication.UnicodeUTF8))
        self.txt_ssh_key.setText(QtGui.QApplication.translate("Frame", "id_dsa", None, QtGui.QApplication.UnicodeUTF8))
        self.txt_ssh_key.setPlaceholderText(QtGui.QApplication.translate("Frame", "Path of auth key", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_ssh_key_dialog.setText(QtGui.QApplication.translate("Frame", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Frame", "Unison Path", None, QtGui.QApplication.UnicodeUTF8))
        self.txt_unison_path.setText(QtGui.QApplication.translate("Frame", "unison", None, QtGui.QApplication.UnicodeUTF8))
        self.txt_unison_path.setPlaceholderText(QtGui.QApplication.translate("Frame", "Path to unison executable", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_unison_path_dialog.setText(QtGui.QApplication.translate("Frame", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_save_2.setText(QtGui.QApplication.translate("Frame", "Test Connection", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Frame", "Status:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Frame", "Errors:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Frame", "Conflicts:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Frame", "Events:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Frame", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Frame", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Frame", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Frame", "Not Running", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Frame", "Profile Type: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Frame", "Unison", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Frame", "Threads:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("Frame", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_start.setText(QtGui.QApplication.translate("Frame", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_save.setText(QtGui.QApplication.translate("Frame", "Save", None, QtGui.QApplication.UnicodeUTF8))

