# About
version: 0.0.2
authors:
    - 'hattwj@yahoo.com'
release_date: '2013-12-11'
homepage: 'https://github.com/hattwj/rainmaker'

# paths
user_dir: '${abspath:~/.rainmaker}'
tmp_dir: '${abspath:${user_dir}/tmp}'
config_path: '${user_dir}/config.yml'
database_path: '${user_dir}/rainmaker.sqlite'


# server / client settings
auth_options:
    key_size: 2048
tcp_server_options: 
    listen_port: 8000
tcp_client_options: {}
udp_server_options:
    listen_port: 9500  # peer discovery
    multicast_group: '224.0.0.1'
    broadcast: True
    broadcast_port: 9500 

# logging
log_level: 'info'
log_levels:
    - info
    - debug
    - warn
    - error
log_style: '%(name)-12s %(levelname)-8s %(message)s'
log_path:  '${tmp_dir}/rainmaker.log'
verbosity: 0

# requires
dependencies:
    - 'watchdog'
    - 'yaml'
    - 'twisted'
    - 'twistar'
    - 'sqlite3'
    - 'ishell'
